### ISSUE TITLE
[INSTALLATION] How do I install this?

### ISSUE THREAD

**Issue by Grape-Boy** [azrafe7/hxOrderedMap#3]
I tried using `haxelib git install hxOrderedMap https://github.com/azrafe7/hxOrderedMap` to install it but it's giving me the error `Error: Could not clone Git repository.` I've also tried installing it manually by creating a folder inside the HaxeToolkit folder with a version folder and `.current` file, but that didn't work (`Type not found : hxOrderedMap.OrderedMap` when trying to import)

So how should I install this?

**Comment by Grape-Boy** [comment]
Didn't find a solution, but what I wanted to do was iterate through a parsed JSON's keys in the same order as they were defined in the file, and found a way to do it:
First I parse the JSON into a Dynamic typed variable, then get the fields/keys using Reflect and put that Array<String> inside another variable. Then I reverse the array with the reverse function.
That gives me the keys in the right order.

**Comment by Grape-Boy** [comment]
Ok so I posted an update comment on how I managed to get the keys in the right order but I spoke too soon.

**Comment by azrafe7** [comment]
Hello @Grape-Boy ,
I think the order of keys you receive from the JSON file cannot be guaranteed (see https://stackoverflow.com/questions/47111058/json-loads-doesnt-keep-order).

And also https://haxe.org/manual/std-Json-parsing.html

**Comment by azrafe7** [comment]
... Or maybe looking at the implementation of  `haxe.format.JsonParser`, and see if you can bend it to your needs 🤔

**Comment by azrafe7** [comment]
And by the way, don't take my word for it... you might get some more insights by posting your use case on  https://community.haxe.org/ where the community could help you😉

**Comment by Grape-Boy** [comment]
> ... Or maybe looking at the implementation of `haxe.format.JsonParser`, and see if you can bend it to your needs 🤔

Honestly that seems like my best bet, I'll copy it and edit it. Thanks!

**Comment by Grape-Boy** [comment]
Update: I did it. I just edited the module to return an `Array<Dynamic>` with the object and an `Array<String>` for the fields. There's probably a better way to do this, but this will do for now.
